// Generated from website pricing.html & scripts/master_single_publications.json
// Official authentic NexcoinPR packages and single media placements.

class NexcoinPackage {
  final String title;
  final String shortTitle;
  final String category;
  final int price;
  final String badge;
  final String traffic;
  final String desc;
  final List<String> pubs;

  const NexcoinPackage({
    required this.title,
    required this.shortTitle,
    required this.category,
    required this.price,
    required this.badge,
    required this.traffic,
    required this.desc,
    required this.pubs,
  });
}

class NexcoinSingleOutlet {
  final String name;
  final String domain;
  final int price;
  final String category;
  final String categoryLabel;
  final String traffic;
  final String turnaround;
  final String focus;
  final String badge;

  const NexcoinSingleOutlet({
    required this.name,
    required this.domain,
    required this.price,
    required this.category,
    required this.categoryLabel,
    required this.traffic,
    required this.turnaround,
    required this.focus,
    required this.badge,
  });
}

const List<NexcoinPackage> kOfficialPackages = [
  NexcoinPackage(
    title: 'The 60 Media Mega Package',
    shortTitle: '60 Media Mega',
    category: 'Mega Syndication',
    price: 7000,
    badge: 'MOST POWERFUL SYNDICATION',
    traffic: 'Total 60 Indexed Publications',
    desc: 'Flood the market with complete coverage across 60 specialized crypto, blockchain, and financial publications. Perfect for token generation events (TGE), major exchange listings, protocol mainnet launches, and institutional fund raises.',
    pubs: [
      'Blockonomi.com',
      'Blockzeit.com',
      'Coinworldstory.com',
      'Coincentral.com',
      'Publish0x.com',
      'Bitnewsbot.com',
      'Mpost.io',
      'Coinfea.com',
      'Cryptodirectories.com',
      'NullTx.com',
      'Cryptosavingexpert.com',
      'Thebittimes.com',
      'CryptoNewsLand.com',
      'Daotimes.com',
      '36crypto.com',
      'TheMerkle.com',
      'Btcpeers.com',
      'FxCryptoNews.com',
      'Thecryptoupdates.com',
      'TheNewsCrypto.com',
      'Cryptoboom.com',
      'Cryptowisser.com',
      'Theblockopedia.com',
      'Techbullion',
      'Coinjournal.net',
      'CaptainAltcoin.com',
      'Chainaffairs.com',
      'Invezz',
      'Crypto-reporter.com',
      'Blockchainaire.com',
      'Blockcrux.com',
      'Cryptobrowser.io',
      'Btcnews.com',
      'Coinedition.com',
      'Livebitcoinnews.com',
      'FintechMode.com',
      'Zycrypto.com',
      'Cryptomode.com',
      'Coinography.com',
      'Analyticsinsight.net',
      'Bitcoin Insider',
      'Memecoinist.com',
      'Moneycheck.com',
      'Coinpaper.com',
      'Cryptofingers.com',
      'Coinsprobe.com',
      'Timestabloid.com',
      'TechAnnouncer.com',
      'Coincu.com',
      'Cryptopress.site',
      'Coinnewsspan.com',
      'kanalcoin.com',
      'Stelareum.io',
      'Namecoinnews.com',
      'Theccpress.com',
      'Coingabbar.com',
      'Capitalbay.news',
      'Bitcoininfonews.com',
      'CoinRoop.com',
      'Cryptomoonpress.com',
    ],
  ),
  NexcoinPackage(
    title: 'ELITE: A',
    shortTitle: 'Elite A (5 Media)',
    category: '5-Media Packs (Series A)',
    price: 20000,
    badge: 'Highest Authority',
    traffic: '22M+ Monthly Traffic',
    desc: 'Top-tier Tier-1 global crypto media powerhouse package for major protocol launches, institutional milestones, and headline crypto news.',
    pubs: [
      'CoinTelegraph',
      'Coindesk.com',
      'TheBlock.co',
      'Beincrypto.com',
      'Watcher.guru',
    ],
  ),
  NexcoinPackage(
    title: 'ELITE: B',
    shortTitle: 'Elite B (5 Media)',
    category: '5-Media Packs (Series B)',
    price: 11000,
    badge: 'Tier-1 Impact',
    traffic: '15M+ Monthly Traffic',
    desc: 'Commanding reach pairing CoinTelegraph and Bitcoin.com with global financial syndication.',
    pubs: [
      'CoinTelegraph',
      'Beincrypto.com',
      'Bitcoin.com',
      'AMBCrypto.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'VIRAL (10 Media)',
    shortTitle: 'Viral 10 Media',
    category: '10-Media Packs',
    price: 8300,
    badge: 'Maximum Organic Reach',
    traffic: '15M+ Monthly Traffic',
    desc: 'Comprehensive 10-outlet onslaught combining institutional crypto desks and mainstream financial giants.',
    pubs: [
      'TheBlock.co',
      'Cryptopolitan',
      'Beincrypto',
      'Bitcoin.com',
      'Bitcoinist',
      'Coingape.com',
      'AMB Crypto',
      'NewsBTC',
      'Investing.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'WEB3 GAMING (10 Media)',
    shortTitle: 'Web3 Gaming',
    category: 'Specialized Niche',
    price: 5299,
    badge: 'Gaming & Metaverse',
    traffic: '10M+ Monthly Traffic',
    desc: 'Bespoke distribution into Web3 gaming portals, play-to-earn communities, and gamer news outlets.',
    pubs: [
      'Gam3s.gg',
      'Playtoearn.com',
      'Chainplay.gg',
      'Beanstalk.io',
      'Gurugamer.com',
      'Gamejolt.com',
      'Gamespace.com',
      'Thenoobgamerz.com',
      'Investing.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'FINTECH & FOREX (10 Media)',
    shortTitle: 'Fintech & Forex',
    category: 'Specialized Niche',
    price: 3999,
    badge: 'Brokers & Fintech',
    traffic: '10M+ Monthly Traffic',
    desc: 'Specialized financial wire targeting forex brokers, trading desks, wealthtech apps, and institutional readers.',
    pubs: [
      'Financemagnates.com',
      'Invezz.com',
      'WalletInvestor.com',
      'Tradingbeasts.com',
      'Moneycheck.com',
      'Forexlive.com',
      'Gov.capital',
      'Financebuzz.net',
      'Investing.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'PREMIUM (10 Media)',
    shortTitle: 'Premium 10 Media',
    category: '10-Media Packs',
    price: 3250,
    badge: 'Popular Value',
    traffic: '5M+ Monthly Traffic',
    desc: 'Deep tech, DeFi, and developer-centric distribution with global financial market presence.',
    pubs: [
      'Hackernoon',
      'Thedefiant.io',
      'Coinedition.com',
      'Mpost.io',
      'Blockonomi',
      'Bravenewcoin.com',
      'Publish0x',
      'Coincu',
      'Investing.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'TECH & INNOVATION (10 Media)',
    shortTitle: 'Tech & Innovation',
    category: 'Specialized Niche',
    price: 2899,
    badge: 'Technology Desks',
    traffic: '10M+ Monthly Traffic',
    desc: 'Reaching technology enthusiasts, software engineers, and digital innovation reporters.',
    pubs: [
      'Techbullion',
      'TechAnnouncer',
      'Hackernoon',
      'Techpanga.com',
      'Techpoint.africa',
      'Techiexpert.com',
      'Alltechmagazine.com',
      '99techpost.com',
      'Investing.com',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'SUPERIOR: A',
    shortTitle: 'Superior A (5 Media)',
    category: '5-Media Packs (Series A)',
    price: 2800,
    badge: 'High Growth',
    traffic: '8M+ Monthly Traffic',
    desc: 'Targeted coverage across prominent crypto news websites and premier mainstream financial wire channels.',
    pubs: [
      'Cryptopolitan.com',
      'Crypto.news',
      'Bitcoinist.com',
      'Hackernoon',
      'Business Insider, AP, Benzinga, MarketWatch syndication',
    ],
  ),
  NexcoinPackage(
    title: 'SUPERIOR: B',
    shortTitle: 'Superior B (5 Media)',
    category: '5-Media Packs (Series B)',
    price: 2650,
    badge: 'Ecosystem Builder',
    traffic: '7M+ Monthly Traffic',
    desc: 'Solid mid-tier visibility focused on Web3 researchers, technical readers, and crypto market watchers.',
    pubs: [
      'Crypto.news',
      'Hackernoon',
      'CoinGape',
      'CoinCheckup',
      'Mpost.io',
    ],
  ),
  NexcoinPackage(
    title: 'STARTER (10 Media)',
    shortTitle: 'Starter 10 Media',
    category: '10-Media Packs',
    price: 2350,
    badge: 'Multi-Outlet Starter',
    traffic: '2M+ Monthly Traffic',
    desc: 'Broad multi-outlet coverage for startup funding rounds and community growth announcements.',
    pubs: [
      'Coingabbar.com',
      'Invezz',
      'Bitcoin Insider',
      'Coinjournal',
      'Thebittimes.com',
      'timestabloid.com',
      'CaptainAltcoin',
      'Theblockopedia.com',
      'Investing.com',
      'Business Insider',
    ],
  ),
  NexcoinPackage(
    title: 'STANDARD: A',
    shortTitle: 'Standard A (5 Media)',
    category: '5-Media Packs (Series A)',
    price: 1100,
    badge: 'Budget Friendly',
    traffic: '1M+ Monthly Traffic',
    desc: 'Essential starter visibility for token updates, feature enhancements, and early-stage blockchain announcements.',
    pubs: [
      'Blockonomi',
      'Techbullion',
      'Publish0x',
      'Coinjournal.net',
      'Bitcoin Insider',
    ],
  ),
  NexcoinPackage(
    title: 'STANDARD: B',
    shortTitle: 'Standard B (5 Media)',
    category: '5-Media Packs (Series B)',
    price: 800,
    badge: 'Lowest Entry Cost',
    traffic: '600K+ Monthly Traffic',
    desc: 'Cost-effective distribution for smaller announcements and persistent indexed search visibility.',
    pubs: [
      'Digital Journal',
      'CaptainAltcoin',
      'TechAnnouncer',
      'Bitcoin Insider',
      'Techbullion',
    ],
  ),
];

const List<NexcoinSingleOutlet> kOfficialSingleOutlets = [
  NexcoinSingleOutlet(
    name: 'Entrepreneur.com',
    domain: 'entrepreneur.com',
    price: 8500,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '18M+ Monthly',
    turnaround: '48-72h',
    focus: 'Global Business, Tech & Leadership',
    badge: 'Pinnacle Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Coindesk',
    domain: 'coindesk.com',
    price: 8000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '12M+ Monthly',
    turnaround: '24-48h',
    focus: 'Flagship Institutional Crypto Journalism',
    badge: 'Tier-1 Benchmark',
  ),
  NexcoinSingleOutlet(
    name: 'Forbes',
    domain: 'forbes.com',
    price: 7500,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '80M+ Monthly',
    turnaround: '48-72h',
    focus: 'World Business, C-Suite & Investing',
    badge: 'Global Benchmark',
  ),
  NexcoinSingleOutlet(
    name: 'Cointelegraph (Full PR)',
    domain: 'cointelegraph.com',
    price: 6999,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '22M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Crypto News Leader & Analysis',
    badge: 'World #1 Crypto News',
  ),
  NexcoinSingleOutlet(
    name: 'Cointelegraph (Lite PR)',
    domain: 'cointelegraph.com',
    price: 3500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '22M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Crypto News Leader & Analysis',
    badge: 'World #1 Crypto News',
  ),
  NexcoinSingleOutlet(
    name: 'Dappradar.com',
    domain: 'dappradar.com',
    price: 2200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'Web3 Dapp Analytics & DeFi Ecosystem',
    badge: 'Dapp Intelligence',
  ),
  NexcoinSingleOutlet(
    name: 'Bitcoin.com',
    domain: 'bitcoin.com',
    price: 2000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '6M+ Monthly',
    turnaround: '24-48h',
    focus: 'Bitcoin, Blockchain & Crypto Economy',
    badge: 'Legacy Crypto Giant',
  ),
  NexcoinSingleOutlet(
    name: 'Decrypt.co',
    domain: 'decrypt.co',
    price: 2000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Web3, Decentralized Tech & AI News',
    badge: 'Tier-1 Crypto',
  ),
  NexcoinSingleOutlet(
    name: 'TheBlock.co',
    domain: 'theblock.co',
    price: 1800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '4M+ Monthly',
    turnaround: '24-48h',
    focus: 'Institutional Research & Crypto Breaking News',
    badge: 'Institutional Grade',
  ),
  NexcoinSingleOutlet(
    name: 'Watcher.guru',
    domain: 'watcher.guru',
    price: 1800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '8M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Whale Alerts & Fast Market Headlines',
    badge: 'Viral Crypto News',
  ),
  NexcoinSingleOutlet(
    name: 'BeInCrypto.com',
    domain: 'beincrypto.com',
    price: 1500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '10M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Crypto News (Multi-Language)',
    badge: 'Top Global Portal',
  ),
  NexcoinSingleOutlet(
    name: 'AMBCrypto.com',
    domain: 'ambcrypto.com',
    price: 1300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '6M+ Monthly',
    turnaround: '24-48h',
    focus: 'Market Analysis & Altcoin Predictions',
    badge: 'High Traffic Portal',
  ),
  NexcoinSingleOutlet(
    name: '99bitcoins.com',
    domain: '99bitcoins.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '2.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Bitcoin Education & Crypto Investing',
    badge: 'Legacy Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Bitcoinist.com',
    domain: 'bitcoinist.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '4M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Market Technical Analysis',
    badge: 'Established 2013',
  ),
  NexcoinSingleOutlet(
    name: 'Coinspeaker.com',
    domain: 'coinspeaker.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'Finance, Tech & Blockchain Market Trends',
    badge: 'High Impact',
  ),
  NexcoinSingleOutlet(
    name: 'Crypto.news',
    domain: 'crypto.news',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '7M+ Monthly',
    turnaround: '24-48h',
    focus: 'Independent Web3, NFT & Blockchain News',
    badge: 'Top News Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoNews.com',
    domain: 'cryptonews.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Multi-Language Crypto News Portal',
    badge: 'Global Media',
  ),
  NexcoinSingleOutlet(
    name: 'NewsBTC.com',
    domain: 'newsbtc.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'Bitcoin Technical Analysis & Market Commentary',
    badge: 'Established 2013',
  ),
  NexcoinSingleOutlet(
    name: 'Thecoinrepublic.com',
    domain: 'thecoinrepublic.com',
    price: 1200,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1.8M+ Monthly',
    turnaround: '24-48h',
    focus: 'Fintech, Blockchain & Web3 Market Coverage',
    badge: 'Comprehensive Coverage',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptoninjas.net',
    domain: 'cryptoninjas.net',
    price: 1100,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1.2M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Markets & Digital Asset Infrastructure',
    badge: 'High Reach',
  ),
  NexcoinSingleOutlet(
    name: 'Blockchain.News',
    domain: 'blockchain.news',
    price: 1000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'High-Authority Crypto & Financial Press',
    badge: 'High Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Ccn.com',
    domain: 'ccn.com',
    price: 1000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto News, Finance & Tech Perspectives',
    badge: 'Legacy Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptointelligence.co.uk',
    domain: 'cryptointelligence.co.uk',
    price: 1000,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'High-Authority Crypto & Financial Press',
    badge: 'High Authority',
  ),
  NexcoinSingleOutlet(
    name: 'FXStreet.com',
    domain: 'fxstreet.com',
    price: 1000,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '6M+ Monthly',
    turnaround: '24-48h',
    focus: 'Foreign Exchange & Macro Trading',
    badge: 'Top Forex Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Webopedia.com',
    domain: 'webopedia.com',
    price: 1000,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '2.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Tech Definitions, Cloud & Computing Reference',
    badge: 'Domain Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptopotato.com',
    domain: 'cryptopotato.com',
    price: 850,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '4M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Market Analysis, News & Guides',
    badge: 'High Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Incrypted.com',
    domain: 'incrypted.com',
    price: 850,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Themarketperiodical.com',
    domain: 'themarketperiodical.com',
    price: 850,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CoinGape.com',
    domain: 'coingape.com',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Coinwire.com',
    domain: 'coinwire.com',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoDaily.co.uk',
    domain: 'cryptodaily.co.uk',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptonews.net',
    domain: 'cryptonews.net',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptoslate',
    domain: 'cryptoslate.com',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '3.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Real-Time Crypto Data & Curated News',
    badge: 'Editorial Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Dailycoin.com',
    domain: 'dailycoin.com',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'U.Today',
    domain: 'u.today',
    price: 800,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'BSC.News',
    domain: 'bsc.news',
    price: 750,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'BNB Chain & Multi-Chain DeFi Ecosystem',
    badge: 'Ecosystem Leader',
  ),
  NexcoinSingleOutlet(
    name: 'CoinCodex.com',
    domain: 'coincodex.com',
    price: 750,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '4M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Price Tracking & Market Intelligence',
    badge: 'Market Tracker',
  ),
  NexcoinSingleOutlet(
    name: 'Thecryptobasic.com',
    domain: 'thecryptobasic.com',
    price: 750,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'BitcoinWorld.co.in',
    domain: 'bitcoinworld.co.in',
    price: 700,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CoinPedia.org',
    domain: 'coinpedia.org',
    price: 700,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptopolitan.com',
    domain: 'cryptopolitan.com',
    price: 700,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Financemagnates.com',
    domain: 'financemagnates.com',
    price: 700,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'FX, Trading Brokers & Fintech Intelligence',
    badge: 'Institutional FX',
  ),
  NexcoinSingleOutlet(
    name: 'Forexlive.com',
    domain: 'forexlive.com',
    price: 700,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'Real-Time FX Trading & Central Banks',
    badge: 'Active Trading Desk',
  ),
  NexcoinSingleOutlet(
    name: 'Coinchapter.com',
    domain: 'coinchapter.com',
    price: 650,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Coindar.org',
    domain: 'coindar.org',
    price: 650,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'The-blockchain.com',
    domain: 'the-blockchain.com',
    price: 650,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Thecoinrise.com',
    domain: 'thecoinrise.com',
    price: 650,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Blockonomi.com',
    domain: 'blockonomi.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Blockchain Tech & Cryptocurrency Guides',
    badge: 'Deep Tech',
  ),
  NexcoinSingleOutlet(
    name: 'Bravenewcoin.com',
    domain: 'bravenewcoin.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Coincentral.com',
    domain: 'coincentral.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CoinCheckup.com',
    domain: 'coincheckup.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Crypto-news-flash.com',
    domain: 'crypto-news-flash.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoBriefing.com',
    domain: 'cryptobriefing.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Independent Web3 Research & Tech News',
    badge: 'Research Focus',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoNewsLand.com',
    domain: 'cryptonewsland.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptonewsz.com',
    domain: 'cryptonewsz.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptotimes.io',
    domain: 'cryptotimes.io',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptowisser.com',
    domain: 'cryptowisser.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Defi-planet.com',
    domain: 'defi-planet.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Insidermonkey.com',
    domain: 'insidermonkey.com',
    price: 600,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'Hedge Fund Data & Market Investment Trends',
    badge: 'Wall Street Intel',
  ),
  NexcoinSingleOutlet(
    name: 'TheCryptoUpdates with CMC',
    domain: 'thecryptoupdates.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '800K+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto News + CoinMarketCap Feed',
    badge: 'CMC Community Feed',
  ),
  NexcoinSingleOutlet(
    name: 'Thedefiant.io',
    domain: 'thedefiant.io',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '800K+ Monthly',
    turnaround: '24-48h',
    focus: 'Decentralized Finance (DeFi) News & Alpha',
    badge: 'DeFi Authority',
  ),
  NexcoinSingleOutlet(
    name: 'Usethebitcoin.com',
    domain: 'usethebitcoin.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Zycrypto.com',
    domain: 'zycrypto.com',
    price: 600,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Established Crypto & Blockchain Media Portal',
    badge: 'Verified Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Coindoo.com',
    domain: 'coindoo.com',
    price: 550,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Moneycheck.com',
    domain: 'moneycheck.com',
    price: 550,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Parameter.io',
    domain: 'parameter.io',
    price: 550,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Blockchainreporter.net',
    domain: 'blockchainreporter.net',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Blockster.com',
    domain: 'blockster.com',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '600K+ Monthly',
    turnaround: '24-48h',
    focus: 'Web3 Social Network & Crypto Media',
    badge: 'Web3 Media',
  ),
  NexcoinSingleOutlet(
    name: 'Coincodecap.com',
    domain: 'coincodecap.com',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinjournal.net',
    domain: 'coinjournal.net',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Invezz.com',
    domain: 'invezz.com',
    price: 500,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'Investing, Trading & Digital Currencies',
    badge: 'Global Investor Hub',
  ),
  NexcoinSingleOutlet(
    name: 'Mpost.io',
    domain: 'mpost.io',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'NullTx.com',
    domain: 'nulltx.com',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'TheMerkle.com',
    domain: 'themerkle.com',
    price: 500,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'WalletInvestor.com',
    domain: 'walletinvestor.com',
    price: 430,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '2.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'AI Price Forecasts & Market Models',
    badge: 'Algorithmic Desk',
  ),
  NexcoinSingleOutlet(
    name: 'AnalyticsInsight.net',
    domain: 'analyticsinsight.net',
    price: 400,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '3M+ Monthly',
    turnaround: '24-48h',
    focus: 'AI, Big Data, Blockchain & Analytics',
    badge: 'Deep Tech',
  ),
  NexcoinSingleOutlet(
    name: 'Blockcrux.com',
    domain: 'blockcrux.com',
    price: 400,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Crypto-economy.com',
    domain: 'crypto-economy.com',
    price: 400,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptonomist.ch',
    domain: 'cryptonomist.ch',
    price: 400,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Daotimes.com',
    domain: 'daotimes.com',
    price: 400,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'TheNewsCrypto.com',
    domain: 'thenewscrypto.com',
    price: 400,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Bitcoininfonews.com',
    domain: 'bitcoininfonews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Bitnewsbot.com',
    domain: 'bitnewsbot.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Blockchainaire.com',
    domain: 'blockchainaire.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Blockzeit.com',
    domain: 'blockzeit.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '500K+ Monthly',
    turnaround: '24-48h',
    focus: 'European Crypto News & Web3 Perspectives',
    badge: 'European Desk',
  ),
  NexcoinSingleOutlet(
    name: 'Btcnews.com',
    domain: 'btcnews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Capitalbay.news',
    domain: 'capitalbay.news',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'CaptainAltcoin.com',
    domain: 'captainaltcoin.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '700K+ Monthly',
    turnaround: '24-48h',
    focus: 'Altcoin Reviews, Trading & Market Signals',
    badge: 'Altcoin Focus',
  ),
  NexcoinSingleOutlet(
    name: 'Coincu.com',
    domain: 'coincu.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '800K+ Monthly',
    turnaround: '24-48h',
    focus: 'Southeast Asia & Global Crypto News',
    badge: 'Regional Hub',
  ),
  NexcoinSingleOutlet(
    name: 'Coinfea.com',
    domain: 'coinfea.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinnewsspan.com',
    domain: 'coinnewsspan.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'coinography.com',
    domain: 'coinography.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'CoinRoop.com',
    domain: 'coinroop.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinsprobe.com',
    domain: 'coinsprobe.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinworldstory.com',
    domain: 'coinworldstory.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptoboom.com',
    domain: 'cryptoboom.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptodirectories.com',
    domain: 'cryptodirectories.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptofingers.com',
    domain: 'cryptofingers.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptomoonpress.com',
    domain: 'cryptomoonpress.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptosavingexpert.com',
    domain: 'cryptosavingexpert.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Ethnews.com',
    domain: 'ethnews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'FintechMode.com',
    domain: 'fintechmode.com',
    price: 350,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Fintech Trends, Digital Banking & Web3',
    badge: 'Fintech News',
  ),
  NexcoinSingleOutlet(
    name: 'FxCryptoNews.com',
    domain: 'fxcryptonews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Multi-Language Crypto News Portal',
    badge: 'Global Media',
  ),
  NexcoinSingleOutlet(
    name: 'kanalcoin.com',
    domain: 'kanalcoin.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Livebitcoinnews.com',
    domain: 'livebitcoinnews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '600K+ Monthly',
    turnaround: '24-48h',
    focus: 'Daily Bitcoin & Cryptocurrency Headlines',
    badge: 'Fast Updates',
  ),
  NexcoinSingleOutlet(
    name: 'memecoinist.com',
    domain: 'memecoinist.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Namecoinnews.com',
    domain: 'namecoinnews.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Publish0x.com',
    domain: 'publish0x.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Publishing & Earn Ecosystem',
    badge: 'Community Hub',
  ),
  NexcoinSingleOutlet(
    name: 'Stelareum.io',
    domain: 'stelareum.io',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'TechAnnouncer.com',
    domain: 'techannouncer.com',
    price: 350,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '500K+ Monthly',
    turnaround: '24-48h',
    focus: 'Tech Startups & Business Announcements',
    badge: 'Syndication Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Thebittimes.com',
    domain: 'thebittimes.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Theccpress.com',
    domain: 'theccpress.com',
    price: 350,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: '36crypto.com',
    domain: '36crypto.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'ABPLive.com',
    domain: 'abplive.com',
    price: 300,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '40M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global News & International Broadcast',
    badge: 'High-Traffic News',
  ),
  NexcoinSingleOutlet(
    name: 'BitcoinInsider.org',
    domain: 'bitcoininsider.org',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Chainaffairs.com',
    domain: 'chainaffairs.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'CoinEdition',
    domain: 'coinedition.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '1.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Crypto Market Intelligence & Altcoins',
    badge: 'Fast Indexing',
  ),
  NexcoinSingleOutlet(
    name: 'Coingabbar.com',
    domain: 'coingabbar.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinpaper.com',
    domain: 'coinpaper.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Crypto-reporter.com',
    domain: 'crypto-reporter.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptobrowser.io',
    domain: 'cryptobrowser.io',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptomode.com',
    domain: 'cryptomode.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Cryptopress.site',
    domain: 'cryptopress.site',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Mirror Review',
    domain: 'mirrorreview.com',
    price: 300,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '500K+ Monthly',
    turnaround: '24-48h',
    focus: 'Business Leadership & Enterprise Tech',
    badge: 'Executive Spotlight',
  ),
  NexcoinSingleOutlet(
    name: 'MSN',
    domain: 'msn.com',
    price: 300,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '200M+ Monthly',
    turnaround: '24-48h',
    focus: 'Microsoft Global News Network',
    badge: 'Massive Reach',
  ),
  NexcoinSingleOutlet(
    name: 'NY Wire',
    domain: 'nywire.com',
    price: 300,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'New York Business & Wall Street PR',
    badge: 'Regional Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Theblockopedia.com',
    domain: 'theblockopedia.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '4M+ Monthly',
    turnaround: '24-48h',
    focus: 'Institutional Research & Crypto Breaking News',
    badge: 'Institutional Grade',
  ),
  NexcoinSingleOutlet(
    name: 'Timestabloid.com',
    domain: 'timestabloid.com',
    price: 300,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Yahoo Finance',
    domain: 'finance.yahoo.com',
    price: 300,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '150M+ Monthly',
    turnaround: '24-48h',
    focus: 'World Financial News & Stock Tickers',
    badge: 'Global Financial Portal',
  ),
  NexcoinSingleOutlet(
    name: 'Blocktelegraph.io',
    domain: 'blocktelegraph.io',
    price: 250,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'Coinreviewnews.com',
    domain: 'coinreviewnews.com',
    price: 250,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '400K+ Monthly',
    turnaround: '24-48h',
    focus: 'Targeted Crypto & Web3 News Indexing',
    badge: 'Indexed Publication',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoDisplay.io',
    domain: 'cryptodisplay.io',
    price: 250,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '300K+ Monthly',
    turnaround: '24-48h',
    focus: 'Token Presales, ICO Listings & Launch Alpha',
    badge: 'Launchpad Wire',
  ),
  NexcoinSingleOutlet(
    name: 'CryptoPresale.xyz',
    domain: 'cryptopresale.xyz',
    price: 250,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '300K+ Monthly',
    turnaround: '24-48h',
    focus: 'Token Presales, ICO Listings & Launch Alpha',
    badge: 'Launchpad Wire',
  ),
  NexcoinSingleOutlet(
    name: 'ICOAnnouncement.io',
    domain: 'icoannouncement.io',
    price: 250,
    category: 'crypto',
    categoryLabel: 'Crypto & Web3',
    traffic: '300K+ Monthly',
    turnaround: '24-48h',
    focus: 'Token Presales, ICO Listings & Launch Alpha',
    badge: 'Launchpad Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Markets.BusinessInsider',
    domain: 'markets.businessinsider.com',
    price: 250,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '30M+ Monthly',
    turnaround: '24-48h',
    focus: 'Institutional Markets & Financial Data',
    badge: 'Institutional Desk',
  ),
  NexcoinSingleOutlet(
    name: 'Benzinga',
    domain: 'benzinga.com',
    price: 150,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '14M+ Monthly',
    turnaround: '24-48h',
    focus: 'Actionable Financial Media & Stocks',
    badge: 'Trading Terminal',
  ),
  NexcoinSingleOutlet(
    name: 'Tekedia',
    domain: 'tekedia.com',
    price: 150,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '600K+ Monthly',
    turnaround: '24-48h',
    focus: 'Technology, Innovation & Economy',
    badge: 'Emerging Markets',
  ),
  NexcoinSingleOutlet(
    name: 'The Globe and Mail',
    domain: 'theglobeandmail.com',
    price: 150,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '12M+ Monthly',
    turnaround: '24-48h',
    focus: 'National Financial News of Record',
    badge: 'Prestigious Press',
  ),
  NexcoinSingleOutlet(
    name: 'AP News (Associated Press)',
    domain: 'apnews.com',
    price: 100,
    category: 'mainstream',
    categoryLabel: 'Mainstream Tier-1',
    traffic: '60M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Newswire & Public Record',
    badge: 'Official Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Barchart.com',
    domain: 'barchart.com',
    price: 100,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Commodities, FX & Market Analytics',
    badge: 'Trading Terminal',
  ),
  NexcoinSingleOutlet(
    name: 'Big News Network',
    domain: 'bignewsnetwork.com',
    price: 100,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '1.5M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global Syndicated News Network',
    badge: 'Global Wire',
  ),
  NexcoinSingleOutlet(
    name: 'Digital Journal',
    domain: 'digitaljournal.com',
    price: 100,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '2M+ Monthly',
    turnaround: '24-48h',
    focus: 'Global News Portal & Syndication',
    badge: 'Google News Feed',
  ),
  NexcoinSingleOutlet(
    name: 'StreetInsider.com',
    domain: 'streetinsider.com',
    price: 100,
    category: 'forex',
    categoryLabel: 'Forex & Trading',
    traffic: '1.2M+ Monthly',
    turnaround: '24-48h',
    focus: 'Wall Street Intelligence & Market Wire',
    badge: 'Wall Street Desk',
  ),
  NexcoinSingleOutlet(
    name: 'TechBullion',
    domain: 'techbullion.com',
    price: 100,
    category: 'tech',
    categoryLabel: 'Tech & Syndication',
    traffic: '1M+ Monthly',
    turnaround: '24-48h',
    focus: 'London Fintech & Tech News',
    badge: 'Fintech Focus',
  ),
];
